{% set version = "1.3.2.0" %}
{% set suitesparse_for_win_version = "7.2.1" %}

# This recipe is based on CVXOPT's recipe:
# https://github.com/conda-forge/cvxopt-feedstock/blob/master/recipe
package:
  name: kvxopt
  version: {{ version }}


source:
  - url: https://pypi.io/packages/source/k/kvxopt/kvxopt-{{ version }}.tar.gz
    sha256: 35d155905c1fcd223418f0f02250e70d77449f382faad3093f339e86f6d5ad41

  # on windows, building suitesparse in directly works much better than trying to build it separately and link it in
  - url: https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/v{{ suitesparse_for_win_version }}.tar.gz  # [win]
    sha256: 304e959a163ff74f8f4055dade3e0b5498d9aa3b1c483633bb400620f521509f  # [win]
    folder: suitesparse  # [win]


build:
  skip: true  # [py<35]
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - libblas
    - liblapack
    - python
    - setuptools
    - gsl
    - fftw
    - dsdp
    - glpk
    - libosqp
    # suitesparse is linked against on windows, and compiled-in on windows, because yeah, windows.
    - suitesparse          # [not win]
    - setuptools_scm  # For versioning
  run:
    - python
    - gsl
    - fftw
    - dsdp
    - glpk
    - libosqp
    - suitesparse          # [not win]
  run_constrained:
    # CVXOPT and KVXOPT can be on the same environment. But include file cvxopt.h not. This can be changed in the future
    - cvxopt ==999999999

test:
  imports:
    - kvxopt
    - kvxopt.base
    - kvxopt.blas
    - kvxopt.cholmod
    - kvxopt.lapack
    - kvxopt.misc_solvers
    - kvxopt.umfpack
    - kvxopt.glpk
    - kvxopt.fftw
    - kvxopt.klu
    - kvxopt.osqp
    - kvxopt.fftw
    - kvxopt.gsl
    - kvxopt.glpk
  source_files:
    - tests/*
    - examples/*
  requires:
    - pytest

about:
  home: https://github.com/sanurielf/kvxopt
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Convex optimization package and Suite Sparse interface
  doc_url: https://github.com/sanurielf/kvxopt
  dev_url: https://github.com/sanurielf/kvxopt

extra:
  recipe-maintainers:
    - sanurielf
