{% set version = "1.3.2.1" %}
{% set suitesparse_for_win_version = "7.7.0" %}

# This recipe is based on CVXOPT's recipe:
# https://github.com/conda-forge/cvxopt-feedstock/blob/master/recipe
package:
  name: kvxopt
  version: {{ version }}


source:
  - url: https://pypi.io/packages/source/k/kvxopt/kvxopt-{{ version }}.tar.gz
    sha256: 312df18c11286a2b0ee582e63474b39f685f494425f70308976a3c46c0e6cb45

  # on windows, building suitesparse in directly works much better than trying to build it separately and link it in
  - url: https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/v{{ suitesparse_for_win_version }}.tar.gz  # [win]
    sha256: 529b067f5d80981f45ddf6766627b8fc5af619822f068f342aab776e683df4f3  # [win]
    folder: suitesparse  # [win]


build:
  skip: true  # [py<35]
  number: 3

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - libblas
    - liblapack
    - python
    - setuptools
    - gsl
    - fftw
    - dsdp
    - glpk
    - libosqp
    # suitesparse is linked against on windows, and compiled-in on windows, because yeah, windows.
    - suitesparse          # [not win]
    - setuptools_scm  # For versioning
  run:
    - python
    - gsl
    - fftw
    - dsdp
    - glpk
    - libosqp
    - suitesparse          # [not win]


test:
  imports:
    - kvxopt
    - kvxopt.base
    - kvxopt.blas
    - kvxopt.cholmod
    - kvxopt.lapack
    - kvxopt.misc_solvers
    - kvxopt.umfpack
    - kvxopt.glpk
    - kvxopt.fftw
    - kvxopt.klu
    - kvxopt.osqp
    - kvxopt.fftw
    - kvxopt.gsl
    - kvxopt.glpk
  source_files:
    - tests/*
    - examples/*
  requires:
    - pytest

about:
  home: https://github.com/sanurielf/kvxopt
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Convex optimization package and Suite Sparse interface
  doc_url: https://github.com/sanurielf/kvxopt
  dev_url: https://github.com/sanurielf/kvxopt

extra:
  recipe-maintainers:
    - sanurielf
